name: Security Scan

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:

  filesystem-scan:
    name: Filesystem Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"


  dockerfile-scan:
    name: Dockerfile Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy Dockerfile scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          scan-ref: docker/Dockerfile
          severity: CRITICAL,HIGH
          exit-code: "1"
